"""'创建群与成员关系表'

Revision ID: 8db0ed17d08e
Revises: 
Create Date: 2019-11-07 16:48:17.316336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8db0ed17d08e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('middle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(length=32), nullable=True),
    sa.Column('member_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('vip_order', 'add_friend_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='添加好友时间',
               existing_nullable=True)
    op.alter_column('vip_order', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='实际价格',
               existing_nullable=True)
    op.alter_column('vip_order', 'app_openid',
               existing_type=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='微信唯一标识',
               existing_nullable=True)
    op.alter_column('vip_order', 'appid',
               existing_type=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='开发者ID(AppID)',
               existing_nullable=True)
    op.alter_column('vip_order', 'channel_code',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='渠道code',
               existing_nullable=True)
    op.alter_column('vip_order', 'channel_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='渠道id',
               existing_nullable=True)
    op.alter_column('vip_order', 'cheese_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='芝士分期课程id',
               existing_nullable=True)
    op.alter_column('vip_order', 'class_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment=None,
               existing_comment='班次id')
    op.alter_column('vip_order', 'coupon',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='优惠券',
               existing_nullable=True)
    op.alter_column('vip_order', 'course_code',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True,
               comment=None,
               existing_comment='课程编号')
    op.alter_column('vip_order', 'course_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment=None,
               existing_comment='课程id')
    op.alter_column('vip_order', 'course_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='课程类型（0 vip课程 1 低价小课）',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('vip_order', 'create_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('vip_order', 'discount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='折扣',
               existing_nullable=True)
    op.alter_column('vip_order', 'headimgurl',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='头像',
               existing_nullable=True)
    op.alter_column('vip_order', 'item_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='商品id',
               existing_nullable=True)
    op.alter_column('vip_order', 'item_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='商品名称',
               existing_nullable=True)
    op.alter_column('vip_order', 'item_sku_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='商品班级id',
               existing_nullable=True)
    op.alter_column('vip_order', 'item_sku_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='商品班级名称',
               existing_nullable=True)
    op.alter_column('vip_order', 'modify_class_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='调班后班级id',
               existing_nullable=True)
    op.alter_column('vip_order', 'modify_class_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='修改班级时间',
               existing_nullable=True)
    op.alter_column('vip_order', 'nickname',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='昵称',
               existing_nullable=True)
    op.alter_column('vip_order', 'no',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True,
               comment=None,
               existing_comment='订单编号（22位随机数）')
    op.alter_column('vip_order', 'openid',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='微信唯一标识',
               existing_nullable=True)
    op.alter_column('vip_order', 'out_order_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='订单id',
               existing_nullable=True)
    op.alter_column('vip_order', 'pay_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='支付时间',
               existing_nullable=True)
    op.alter_column('vip_order', 'points',
               existing_type=mysql.INTEGER(display_width=10),
               comment=None,
               existing_comment='积分',
               existing_nullable=True)
    op.alter_column('vip_order', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='原价格',
               existing_nullable=True)
    op.alter_column('vip_order', 'qr_code',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='权重二维码',
               existing_nullable=True)
    op.alter_column('vip_order', 'remark',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)
    op.alter_column('vip_order', 'seller_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='销售id',
               existing_nullable=True)
    op.alter_column('vip_order', 'seller_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='销售名称',
               existing_nullable=True)
    op.alter_column('vip_order', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment=None,
               existing_comment='0 待付款 1 处理中（如分期支付，订金，尾款支付，完成了部分支付）2 已付款 3 超时 4 退款 5 部分退款 6已取消',
               existing_server_default=sa.text("'0'"))
    op.alter_column('vip_order', 'track_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户池id',
               existing_nullable=True)
    op.alter_column('vip_order', 'track_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='用户池名称',
               existing_nullable=True)
    op.alter_column('vip_order', 'type',
               existing_type=mysql.INTEGER(display_width=1),
               comment=None,
               existing_comment='0线上订单1线下订单',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('vip_order', 'unionid',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='微信唯一标识',
               existing_nullable=True)
    op.alter_column('vip_order', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户id',
               existing_nullable=True)
    op.drop_table_comment(
        'vip_order',
        existing_comment='订单',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'vip_order',
        '订单',
        existing_comment=None,
        schema=None
    )
    op.alter_column('vip_order', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户id',
               existing_nullable=True)
    op.alter_column('vip_order', 'unionid',
               existing_type=mysql.VARCHAR(length=32),
               comment='微信唯一标识',
               existing_nullable=True)
    op.alter_column('vip_order', 'type',
               existing_type=mysql.INTEGER(display_width=1),
               comment='0线上订单1线下订单',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('vip_order', 'track_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='用户池名称',
               existing_nullable=True)
    op.alter_column('vip_order', 'track_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户池id',
               existing_nullable=True)
    op.alter_column('vip_order', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment='0 待付款 1 处理中（如分期支付，订金，尾款支付，完成了部分支付）2 已付款 3 超时 4 退款 5 部分退款 6已取消',
               existing_server_default=sa.text("'0'"))
    op.alter_column('vip_order', 'seller_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='销售名称',
               existing_nullable=True)
    op.alter_column('vip_order', 'seller_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='销售id',
               existing_nullable=True)
    op.alter_column('vip_order', 'remark',
               existing_type=mysql.VARCHAR(length=100),
               comment='备注',
               existing_nullable=True)
    op.alter_column('vip_order', 'qr_code',
               existing_type=mysql.VARCHAR(length=255),
               comment='权重二维码',
               existing_nullable=True)
    op.alter_column('vip_order', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='原价格',
               existing_nullable=True)
    op.alter_column('vip_order', 'points',
               existing_type=mysql.INTEGER(display_width=10),
               comment='积分',
               existing_nullable=True)
    op.alter_column('vip_order', 'pay_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment='支付时间',
               existing_nullable=True)
    op.alter_column('vip_order', 'out_order_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='订单id',
               existing_nullable=True)
    op.alter_column('vip_order', 'openid',
               existing_type=mysql.VARCHAR(length=32),
               comment='微信唯一标识',
               existing_nullable=True)
    op.alter_column('vip_order', 'no',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False,
               comment='订单编号（22位随机数）')
    op.alter_column('vip_order', 'nickname',
               existing_type=mysql.VARCHAR(length=255),
               comment='昵称',
               existing_nullable=True)
    op.alter_column('vip_order', 'modify_class_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment='修改班级时间',
               existing_nullable=True)
    op.alter_column('vip_order', 'modify_class_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='调班后班级id',
               existing_nullable=True)
    op.alter_column('vip_order', 'item_sku_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='商品班级名称',
               existing_nullable=True)
    op.alter_column('vip_order', 'item_sku_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='商品班级id',
               existing_nullable=True)
    op.alter_column('vip_order', 'item_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='商品名称',
               existing_nullable=True)
    op.alter_column('vip_order', 'item_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='商品id',
               existing_nullable=True)
    op.alter_column('vip_order', 'headimgurl',
               existing_type=mysql.VARCHAR(length=255),
               comment='头像',
               existing_nullable=True)
    op.alter_column('vip_order', 'discount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='折扣',
               existing_nullable=True)
    op.alter_column('vip_order', 'create_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('vip_order', 'course_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='课程类型（0 vip课程 1 低价小课）',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('vip_order', 'course_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment='课程id')
    op.alter_column('vip_order', 'course_code',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False,
               comment='课程编号')
    op.alter_column('vip_order', 'coupon',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='优惠券',
               existing_nullable=True)
    op.alter_column('vip_order', 'class_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment='班次id')
    op.alter_column('vip_order', 'cheese_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='芝士分期课程id',
               existing_nullable=True)
    op.alter_column('vip_order', 'channel_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='渠道id',
               existing_nullable=True)
    op.alter_column('vip_order', 'channel_code',
               existing_type=mysql.VARCHAR(length=32),
               comment='渠道code',
               existing_nullable=True)
    op.alter_column('vip_order', 'appid',
               existing_type=mysql.VARCHAR(length=36),
               comment='开发者ID(AppID)',
               existing_nullable=True)
    op.alter_column('vip_order', 'app_openid',
               existing_type=mysql.VARCHAR(length=36),
               comment='微信唯一标识',
               existing_nullable=True)
    op.alter_column('vip_order', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='实际价格',
               existing_nullable=True)
    op.alter_column('vip_order', 'add_friend_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment='添加好友时间',
               existing_nullable=True)
    op.drop_table('middle')
    # ### end Alembic commands ###
