"""新增VipSeller表

Revision ID: 9126bb4a0ddc
Revises: 
Create Date: 2019-11-12 00:08:52.735963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9126bb4a0ddc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('middle')
    op.alter_column('vip_order', 'add_friend_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='??????',
               existing_nullable=True)
    op.alter_column('vip_order', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='????',
               existing_nullable=True)
    op.alter_column('vip_order', 'app_openid',
               existing_type=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='??????',
               existing_nullable=True)
    op.alter_column('vip_order', 'appid',
               existing_type=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='???ID(AppID)',
               existing_nullable=True)
    op.alter_column('vip_order', 'channel_code',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='??code',
               existing_nullable=True)
    op.alter_column('vip_order', 'channel_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='??id',
               existing_nullable=True)
    op.alter_column('vip_order', 'cheese_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='??????id',
               existing_nullable=True)
    op.alter_column('vip_order', 'class_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment=None,
               existing_comment='??id')
    op.alter_column('vip_order', 'coupon',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='???',
               existing_nullable=True)
    op.alter_column('vip_order', 'course_code',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True,
               comment=None,
               existing_comment='????')
    op.alter_column('vip_order', 'course_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment=None,
               existing_comment='??id')
    op.alter_column('vip_order', 'course_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='?????0 vip?? 1 ?????',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('vip_order', 'create_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='????',
               existing_nullable=True)
    op.alter_column('vip_order', 'discount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='??',
               existing_nullable=True)
    op.alter_column('vip_order', 'headimgurl',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='??',
               existing_nullable=True)
    op.alter_column('vip_order', 'item_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='??id',
               existing_nullable=True)
    op.alter_column('vip_order', 'item_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='????',
               existing_nullable=True)
    op.alter_column('vip_order', 'item_sku_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='????id',
               existing_nullable=True)
    op.alter_column('vip_order', 'item_sku_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='??????',
               existing_nullable=True)
    op.alter_column('vip_order', 'modify_class_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='?????id',
               existing_nullable=True)
    op.alter_column('vip_order', 'modify_class_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='??????',
               existing_nullable=True)
    op.alter_column('vip_order', 'nickname',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='??',
               existing_nullable=True)
    op.alter_column('vip_order', 'no',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True,
               comment=None,
               existing_comment='?????22?????')
    op.alter_column('vip_order', 'openid',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='??????',
               existing_nullable=True)
    op.alter_column('vip_order', 'out_order_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='??id',
               existing_nullable=True)
    op.alter_column('vip_order', 'pay_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='????',
               existing_nullable=True)
    op.alter_column('vip_order', 'points',
               existing_type=mysql.INTEGER(display_width=10),
               comment=None,
               existing_comment='??',
               existing_nullable=True)
    op.alter_column('vip_order', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='???',
               existing_nullable=True)
    op.alter_column('vip_order', 'qr_code',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='?????',
               existing_nullable=True)
    op.alter_column('vip_order', 'remark',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='??',
               existing_nullable=True)
    op.alter_column('vip_order', 'seller_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='??id',
               existing_nullable=True)
    op.alter_column('vip_order', 'seller_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='????',
               existing_nullable=True)
    op.alter_column('vip_order', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment=None,
               existing_comment='0 ??? 1 ??????????????????????????2 ??? 3 ?? 4 ?? 5 ???? 6???',
               existing_server_default=sa.text("'0'"))
    op.alter_column('vip_order', 'track_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='???id',
               existing_nullable=True)
    op.alter_column('vip_order', 'track_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='?????',
               existing_nullable=True)
    op.alter_column('vip_order', 'type',
               existing_type=mysql.INTEGER(display_width=1),
               comment=None,
               existing_comment='0????1????',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('vip_order', 'unionid',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='??????',
               existing_nullable=True)
    op.alter_column('vip_order', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='??id',
               existing_nullable=True)
    op.drop_table_comment(
        'vip_order',
        existing_comment='??',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'vip_order',
        '??',
        existing_comment=None,
        schema=None
    )
    op.alter_column('vip_order', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='??id',
               existing_nullable=True)
    op.alter_column('vip_order', 'unionid',
               existing_type=mysql.VARCHAR(length=32),
               comment='??????',
               existing_nullable=True)
    op.alter_column('vip_order', 'type',
               existing_type=mysql.INTEGER(display_width=1),
               comment='0????1????',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('vip_order', 'track_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='?????',
               existing_nullable=True)
    op.alter_column('vip_order', 'track_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='???id',
               existing_nullable=True)
    op.alter_column('vip_order', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment='0 ??? 1 ??????????????????????????2 ??? 3 ?? 4 ?? 5 ???? 6???',
               existing_server_default=sa.text("'0'"))
    op.alter_column('vip_order', 'seller_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='????',
               existing_nullable=True)
    op.alter_column('vip_order', 'seller_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='??id',
               existing_nullable=True)
    op.alter_column('vip_order', 'remark',
               existing_type=mysql.VARCHAR(length=100),
               comment='??',
               existing_nullable=True)
    op.alter_column('vip_order', 'qr_code',
               existing_type=mysql.VARCHAR(length=255),
               comment='?????',
               existing_nullable=True)
    op.alter_column('vip_order', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='???',
               existing_nullable=True)
    op.alter_column('vip_order', 'points',
               existing_type=mysql.INTEGER(display_width=10),
               comment='??',
               existing_nullable=True)
    op.alter_column('vip_order', 'pay_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment='????',
               existing_nullable=True)
    op.alter_column('vip_order', 'out_order_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='??id',
               existing_nullable=True)
    op.alter_column('vip_order', 'openid',
               existing_type=mysql.VARCHAR(length=32),
               comment='??????',
               existing_nullable=True)
    op.alter_column('vip_order', 'no',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False,
               comment='?????22?????')
    op.alter_column('vip_order', 'nickname',
               existing_type=mysql.VARCHAR(length=255),
               comment='??',
               existing_nullable=True)
    op.alter_column('vip_order', 'modify_class_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment='??????',
               existing_nullable=True)
    op.alter_column('vip_order', 'modify_class_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='?????id',
               existing_nullable=True)
    op.alter_column('vip_order', 'item_sku_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='??????',
               existing_nullable=True)
    op.alter_column('vip_order', 'item_sku_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='????id',
               existing_nullable=True)
    op.alter_column('vip_order', 'item_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='????',
               existing_nullable=True)
    op.alter_column('vip_order', 'item_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='??id',
               existing_nullable=True)
    op.alter_column('vip_order', 'headimgurl',
               existing_type=mysql.VARCHAR(length=255),
               comment='??',
               existing_nullable=True)
    op.alter_column('vip_order', 'discount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='??',
               existing_nullable=True)
    op.alter_column('vip_order', 'create_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment='????',
               existing_nullable=True)
    op.alter_column('vip_order', 'course_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='?????0 vip?? 1 ?????',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('vip_order', 'course_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment='??id')
    op.alter_column('vip_order', 'course_code',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False,
               comment='????')
    op.alter_column('vip_order', 'coupon',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='???',
               existing_nullable=True)
    op.alter_column('vip_order', 'class_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment='??id')
    op.alter_column('vip_order', 'cheese_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='??????id',
               existing_nullable=True)
    op.alter_column('vip_order', 'channel_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='??id',
               existing_nullable=True)
    op.alter_column('vip_order', 'channel_code',
               existing_type=mysql.VARCHAR(length=32),
               comment='??code',
               existing_nullable=True)
    op.alter_column('vip_order', 'appid',
               existing_type=mysql.VARCHAR(length=36),
               comment='???ID(AppID)',
               existing_nullable=True)
    op.alter_column('vip_order', 'app_openid',
               existing_type=mysql.VARCHAR(length=36),
               comment='??????',
               existing_nullable=True)
    op.alter_column('vip_order', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='????',
               existing_nullable=True)
    op.alter_column('vip_order', 'add_friend_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment='??????',
               existing_nullable=True)
    op.create_table('middle',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('class_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('member_id', mysql.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
